### ISSUE TITLE
Static classes compile without package name

### ISSUE THREAD

**Issue by peteshand** [RandoriAS/randori-compiler#86] opened 2013-06-03 00:52 UTC
When using a static classes, randori seems to compile it without the package name.
for example in the threejs interop library, if you use:

AS:
var texture:Texture = ImageUtils.loadTexture( 'images/crate.gif' );

the output is as follows:

JS:
var texture = ImageUtils.loadTexture("images\/crate.gif");

However based on the metadata [JavaScript(export="false", name="THREE.ImageUtils")]
it should be:
var texture = THREE.ImageUtils.loadTexture("images\/crate.gif");

**Comment by labriola** [comment] 2013-06-03 03:33
Pete, I think this is a duplicate of https://github.com/RandoriAS/randori-compiler/issues/37. @teotigraphix can verify, but it should be fixed when the team produces a new plugin... I am going to push for a new plugin with the compiler fixes (and without the bundle work) in the next day or so.

**Comment by teotigraphix** [comment] 2013-06-03 10:19
@peteshand @labriola Yes, this is fixed. Pete, unfortunately there was a major amount of work done in the plugin with bundles/compiler which took weeks. The command line compiler was being updated accordingly but the plugins compiler has not be updated since the plugin was released in mid April.

There is a next version of the plugin that is being tested with many many fixes and bundle support. So all the bugs from mid April will then be fixed in the plugin's compiler.

**Closed as completed by teotigraphix** 2013-06-03 10:19 UTC

**Comment by peteshand** [comment] 2013-06-04 00:39
Awesome, I can live with the command line compiler being up to date for the time being :D
