### ISSUE TITLE
Using "-source-path" compiler argument doesn't seem to work.

### ISSUE THREAD

**Issue by renaun** [RandoriAS/randori-compiler#57] opened 2013-05-17 06:08 UTC
randori.sh - Script that calls compiler
src/SomeClass.as
src_other/SomeClassB.as 

The call in randori.sh looks like this:
java -jar /path/to/randori.jar randori.compiler.clients.Randori -library-path /path/to/swcs/builtin.swc -source-path ./src -js-classes-as-files=true -output ./out

I have tried different values in the -source-path:
-source-path=./src
-source-path=src/
-source-path=/full/path/src

This is on Mac OSX 10.8 with compiler version 0.2.4.1

Error:
The error is that it goes and searches all the folders for .as files. Meaning it tries to compile both src/SomeClass.as and src_other/SomeClassB.as as src.SomeClass and src_other.SomeClassB.

Expected:
Should compile just src/SomeClass.as as SomeClass

**Comment by teotigraphix** [comment] 2013-05-17 10:56
@renaun  This is not an error I don't believe. This implementation is from the Falcon compiler framework and thoroughly tested.

There has to be something we are missing with the relative root. I guess I would need an exact directory and compiler structure to know what is going on. You are the first ever to run into any problems with core compiler arguments.

All File paths are run through the file normalization utilities.

I won't consider this a bug until I can reproduce it.

**Comment by renaun** [comment] 2013-05-17 17:12
Here is some code:
https://dl.dropboxusercontent.com/u/613378/CompilerSourcePathTest.zip

I have:
path1/HelloWorld.as
path2/SomeClass.as

I run the compiler from ./ with a source-path of ./path1

I expect it to just compile the HelloWorld.as class but it does something else. Is my expectation off?

**Comment by teotigraphix** [comment] 2013-05-17 17:25
Well I get what you are saying but this has to do with how you are calling the compiler with relative paths.

Some how the class loader of Java is thinking the execution is happening not where you are adding the relative paths. If you are using relative paths, my first guess would be that it must be from the same folder the jar of the compiler is located. Which this does not look like that.

**Comment by renaun** [comment] 2013-05-17 17:27
I tried full path too and it didn't work, so instead of ./path1 I had /path/to/path1

**Comment by teotigraphix** [comment] 2013-05-17 17:35
I'm thinking there is some other error going on that is not getting logged.

I will look into it.

**Comment by teotigraphix** [comment] 2013-05-17 17:36
It doesn't say anything in the console right? Produces nothing correct? Or do you see ...seconds or something like that.

**Comment by teotigraphix** [comment] 2013-05-17 17:39
@renaun Hey,

```
# Run Randoir Compiler:
java -jar $rc/randori.jar randori.compiler.clients.Randori -sdk-path=$rsdk -source-path $source -js-classes-as-files=true -output $output
```

Is there any reason you are leaving out the equals sign? 

Use this and tell me;

```
# Run Randoir Compiler:
java -jar $rc/randori.jar randori.compiler.clients.Randori -sdk-path=$rsdk -source-path=$source -js-classes-as-files=true -output=$output
```

**Comment by teotigraphix** [comment] 2013-05-17 17:40
@renaun If the above still doesn't work, try putting quotes around all the strings just for one last test.

**Comment by renaun** [comment] 2013-05-17 17:44
Try all those combinations, still no luck. Here is what my call looks like:

CompilerSourcePathTest renaun$ ./randori.sh 
java -jar /Code/WebRelated/RandoriRepos/randori-compiler-0.2.4.2/randori.jar randori.compiler.clients.Randori -sdk-path=/Code/WebRelated/RandoriRepos/randori-sdk/ -source-path=/Code/WebRelated/RandoriExamples/CompilerSourcePathTest/path1 -js-classes-as-files=true -output ./randori-output
Overlapping source path entries: /Code/WebRelated/RandoriExamples/CompilerSourcePathTest is an ancestor of /Code/WebRelated/RandoriExamples/CompilerSourcePathTest/path1

/Code/WebRelated/RandoriExamples/CompilerSourcePathTest/path2/SomeClass.as:3
An externally-visible definition with the name 'SomeClass' was unexpectedly found.
public class SomeClass
             ^

/Code/WebRelated/RandoriExamples/CompilerSourcePathTest/path1/HelloWorld.as:3
Duplicate class definition: HelloWorld.
public class HelloWorld
^

/Code/WebRelated/RandoriExamples/CompilerSourcePathTest/path1/HelloWorld.as
No externally-visible definition with the name 'path1.HelloWorld' was found.

/Code/WebRelated/RandoriExamples/CompilerSourcePathTest/path2/SomeClass.as
No externally-visible definition with the name 'path2.SomeClass' was found.

/Code/WebRelated/RandoriExamples/CompilerSourcePathTest/path1/HelloWorld.as:3
An externally-visible definition with the name 'HelloWorld' was unexpectedly found.
public class HelloWorld
             ^

0.991979 seconds

I just noticed the one line above "Overlapping source path entries: /Code/WebRelated/RandoriExamples/CompilerSourcePathTest is an ancestor of /Code/WebRelated/RandoriExamples/CompilerSourcePathTest/path1" that might be the issue

**Comment by teotigraphix** [comment] 2013-05-21 14:51
I am closing this as its not a bug right now. We are bound to what the current compiler config framework will accept for paths.

**Closed as completed by teotigraphix** 2013-05-21 14:51 UTC
Labels: question
